### ISSUE TITLE
Autosave Web resource

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#102]
Have an autosave feature, so that if the user is signed-in and autosave is enabled, it can autosave the resource at certain intervals. Requested by @timbl 

Autosaving is available for the local storage feature, so we might just have to generalize it in order to have it both write to URLs as well as work for browser's local storage.

**Comment by megoth** [comment]
This is already implemented I think? (Might want to close this issue is what I was thinking about ^_^ )

**Comment by csarven** [comment]
Thanks for the notice. If only I was professional enough to remember or check what's documented here =)

**Comment by csarven** [comment]
Noting here that the current implementation seems to meet the ATAG Guideline "A.3.2.4 Content Edits Saved (Extended)":
https://www.w3.org/TR/ATAG20/#sc_a324 ( https://www.w3.org/TR/IMPLEMENTING-ATAG20/#sc_a324 )

I think it also meets https://www.w3.org/TR/ATAG20/#sc_a321 ( https://www.w3.org/TR/IMPLEMENTING-ATAG20/#sc_a321 ) however I'm not sure if it would be required to show a prompt/alert when closing the browser. That's even if auto-save is on and set to 1m interval, it is possible to lose some work.

Minor todo: Leaving the "Edit" mode commits the changes to the DOM but not to localStorage or http.
