### ISSUE TITLE
Send a notification to an existing article (target) from an article (source)

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#112]
You see an article you want to reply to, but your reply is longer than a little annotation on the side. You create a new dokieli document (hosted anywhere) so you can write your long reply as an article. You need somewhere to say what this article is in reply to, and have dokieli send a ping to the [inbox of the] original when you input this.

Related to https://github.com/linkeddata/dokieli/issues/110

**Comment by csarven** [comment]
https://github.com/linkeddata/dokieli/issues/398 implements user inputting in-reply-to URL. Todo:

* [ ] have dokieli send notifications to in-reply-to 's inbox.

Noting here that this is similar how citations currently work. When something is cited and that cited entity has its own inbox, dokieli will automatically send a notification to that inbox.

**Comment by csarven** [comment]
Closing in favour of https://github.com/linkeddata/dokieli/issues/400 for the remaining part - same same but different.
