### ISSUE TITLE
sign-in button activation

### ISSUE THREAD

**Issue by sandhawke** [dokieli/dokieli#121]
In the Sign-In popup, the Sign In button remains greyed out even after I mouse-paste in my webid, presumably because you're looking for a keyboard event and I never use the keyboard.  Also, same thing, if I use the browser-form-value-history via the mouse instead of the keyboard.

**Comment by csarven** [comment]
With the recent updates:

Mouse paste should work as requested. Keyboard paste works in the same way.

In addition to that, if the user selects an autocomplete value (provided that the browser remembers and reveals previous form values) with:
1. mouse, it will enable the submit button (provided that it starts off with the http(s)://), i.e., the submit is no longer disables/greyed out.
2. keyboard enter, it will auto-submit - I'm not sure if this is a bug or a feature, but I'm going to leave it as such for now until there is a complaint :)
