### ISSUE TITLE
Displaying annotations served from different domains

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#122]
For all annotations served from servers which wants to do authentication, the user will be prompted for each annotation on every different domain. This is an undesirable (or a terrible) UX.

**Comment by rhiaro** [comment]
This might need to be resolved with changes at a Solid level. ie. if I'm authenticated with my server, my server could then do all the authentication and fetching with other servers in the background, so the user isn't bothered by it.

If a user is _not_ authenticated, and has no certs, it'll just fetch stuff that's public/acl-free with no cert popups, which is fine. However, if a user doesn't have a _WebID cert_ but does have other certs in their browser, they're still going to be harassed by a cert popup per domain for GETs on every resource with ACL...

This is going to be a problem for any UI that pulls data in from lots of different sources. How did CIMBA handle it?

Who invited browser certs? :p

cc @deiu @nicola @sandhawke @dmitrizagidulin

**Comment by csarven** [comment]
This is no longer an issue with https://github.com/solid/node-solid-server i.e., for resources with public read, there is no cert prompt. However, it is still the case with https://github.com/linkeddata/gold . I can live with this for now. I'm not sure if this issue (when dealing with WebID+TLS+browser behaviour) can be fixed in the foreseeable future. WONTFIX / Leave it open?

**Comment by RubenVerborgh** [comment]
> for resources with public read, there is no cert prompt

Are you sure? Because the cert prompt happens at TLS negotiation, _before_ the server is able to see the HTTP request and the path. Hence, the solid server can only determine whether a resource is publicly readable after the prompt has already been shown.

**Comment by csarven** [comment]
I really can't recall exactly given the timeframe of things and the state of the servers.. but my assumption right now is that the server didn't bother with negotiation *if* the resource was public read.

**Comment by RubenVerborgh** [comment]
> the server didn't bother with negotiation _if_ the resource was public read

That's not possible, as TLS negotiation happens before the HTTP request line is sent, i.e., before the server can figure out whether a resource is public read. Dropping the negotiation is only possible if the entire server is public read.

**Comment by csarven** [comment]
That's only under the assumption that the TLS connection is made right away. Alternatively, the server can use *TLS renegotiation* by "moving the authentication to the application layer Guard which can make more fine grained decisions on when authentication is required" - https://www.w3.org/2005/Incubator/webid/spec/tls/#h_note_2 . This fits the observation that's described for node-solid-server in https://github.com/linkeddata/dokieli/issues/122#issuecomment-241305358 . That may not be what's actually happening with node-solid-server, but I'm only describing the observation here. I think @dmitrizagidulin or @nicola can best confirm this (current or old) behaviour for node-solid-server.

**Comment by RubenVerborgh** [comment]
I've worked with the auth part of node-solid-server, and can confirm it performs upfront negotiation.

**Comment by RubenVerborgh** [comment]
Here you can see that the server requests up-front negotiation: https://github.com/solid/node-solid-server/blob/v3.5.1/lib/create-server.js#L62 by always setting the `requestCert` option.

Currently, this can not be changed by any of the handlers, since the entire request handling process is implemented as a pipeline where the lower layers do not know about the higher (= authentication) layers. We had to slightly change this for `PATCH`, which needs to check specific permissions down the stream (https://github.com/solid/node-solid-server/blob/rv/patch/n3/lib/handlers/patch.js#L52), but even that does not change the auth negotiation from occurring.

**Comment by csarven** [comment]
Going to resolve this issue by saying that there is nothing in particular that dokieli can do here with servers which have an upfront requirement from clients to provide their certificate. As this issue illustrates the undesired (server-client [browser] triggered) UX, it is preferable that servers do TLS renegotiation (as mentioned in the WebID-TLS spec). That way, resources that have a public acl:Read policy are not bothered - that may or may not be a design that "Solid" servers want to enforce. In any case, out of scope for dokieli since it is the current Web browser behaviour that's a bother, and at the same time nothing dokieli can do about it.

**Comment by RubenVerborgh** [comment]
For future reference, Node.js does support renegotiation: https://nodejs.org/api/tls.html#tls_tlssocket_renegotiate_options_callback

**Comment by csarven** [comment]
This issue (dokieli annotations/Solid servers, and cert prompts) was discussed previously. The consensus (as I recall) was to not bother the user for public read resources. It'd be great if node-solid-server either sets the default behaviour to not force upfront negotiation, or makes it possible to configure. I can understand why the server out of the box may want to force that, but it should be possible to change it in node-solid-server config.json.

**Comment by RubenVerborgh** [comment]
Agree that this is best. Perhaps post an issue for it?
Definitely configurable, as renegotiation will not work behind a proxy (https://github.com/solid/node-solid-server/wiki/Running-Solid-behind-a-reverse-proxy).
