### ISSUE TITLE
Name not resolved errors not caught

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#123]
In places a URL is entered as a string by the user, if it's not a real tld, or it exists (_not_ 404) but has a server/DNS misconfiguration (or something) that makes it unreachable, the result is Error: Name Not Resolved. I haven't figured out how to catch these from simpleRDF's GET yet, but we need to deal with these as the only feedback is in the console right now.

**Comment by csarven** [comment]
Closing issue in favour of more specific https://github.com/linkeddata/dokieli/issues/384 - same same but different.
