### ISSUE TITLE
Drop Workspaces discovery for storing annotations

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#127]
Currently the profile is checked for various different types of Workspace to choose where to store annotations. Workspaces are being dropped in Solid, and the default containers are server-implementation-specific, so storage location should just be up to the user (per #59 and #60), though we do possibly need some way of coming up with a sensible default in case they don't care.

**Comment by csarven** [comment]
The default is set to the storage URI.

Will create a new issue (if not already one) to select a location at the time of saving/annotating. It'll incorporate resource browser.
