### ISSUE TITLE
testing on math-heavy documents

### ISSUE THREAD

**Issue by pfps** [dokieli/dokieli#13]
Mathematics is a problem for HTML, even with MathML. 

There should be comprehensive testing on math-heavy documents.

**Comment by csarven** [comment]
I think it would be best to have a test suite for this. Would you mind mentioning some formulas?

I have included some initial MathML usage. See https://dokie.li/acm-sigproc-sp for example.

As for non-MathML e.g., MathJax, I'd like to treat that as a separate feature. Right now, I'd like to identify how the issue you've raised here can be tested for and eventually complied with.

**Comment by csarven** [comment]
dokieli includes MathJax ( https://dokie.li/docs#html-math ) which allows (La)Tex and ASCIIMath syntax as input and gets rendered properly.
