### ISSUE TITLE
Disable/hide save when not actually available

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#137]
Save is available when:
1. Local storage is enabled (but currently this is a separate button and has autosave)
2. Article is on a public-writeable storage location
3. Article is on a storage location writeable by currently signed in user

2 Might be particularly hard to detect. Can we do a `HEAD` on document load (_without_ triggering a cert popup) to find this out?

**Comment by csarven** [comment]
See also #259 for one possible way to have this work.

**Comment by csarven** [comment]
Uhh.. pardon me, I got a bit distracted there..

This is now implemented using the `WAC-Allow` header. Brief detail/screenshots: https://github.com/linkeddata/dokieli/issues/259#issuecomment-734766140
