### ISSUE TITLE
WebKit not switching stylesheet at first

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#162]
For some reason Chromium (last tested on `Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.10 (64-bit)`) doesn't change the stylesheet immediately (any longer) when clicked on a style. For example, if 'LNCS' is clicked, while the HTML link is updated correctly, the UI acts as if no stylesheet is loaded. If then continue to click 'ACM', it shows the ACM stylesheet. If 'LNCS' is clicked again, it works. Firefox 49.0/Ubuntu 16.10 has no issues.

**Comment by jodischneider** [comment]
Tested today on Safari Version 10.0.3 (12602.4.8) under Mac OS X 10.12.3 (16D32). The first stylesheet click after loading the page results in a no-stylesheet version. Subsequent clicks on a second, third, etc, stylesheet work as expected (i.e. I see the expected styling).

**Comment by csarven** [comment]
Thanks for reporting. It is an annoying glitch with some browsers. Firefox is okay for instance. I'll probably have to change that around a bit so that there are no surprises in the interface.

**Comment by csarven** [comment]
I've pushed some updates which appears to resolve the WebKit issue (in Chromium at least). It may resolve it for Safari as well. Would you mind checking?

**Comment by jodischneider** [comment]
Stylesheets now work as expected in Mac Safari Version 10.1.1 (12603.2.4)!

**Comment by csarven** [comment]
Thank you for helping to resolve this issue.
