### ISSUE TITLE
Load CSS of a dokieli with URL parameter

### ISSUE THREAD

**Issue by jibe-b** [dokieli/dokieli#163]
In the style of 

>?style=https://dokie.li/media/css/acm.css
(some work done by @csarven already)

a dokieli page would be loaded with the css style sheet indicated as a value of stype

Possible starting point:
https://github.com/linkeddata/dokieli/blob/main/scripts/do.js#L1399

**Comment by csarven** [comment]
After updating the DOM, I think it might be good to update the URL state like:

`window.history.replaceState({}, null, document.location.href.substr(0, document.location.href.lastIndexOf('?')));`

**Comment by csarven** [comment]
`style` parameter value can be an IRI and so it fetches (on the client-side) and sets that as the current stylesheet, or it can be the title of the stylesheet that's already in the document. Examples:

* https://dokie.li/?style=http://csarven.ca/media/css/index.css
* https://dokie.li/?style=https://www.w3.org/DesignIssues/di.css

* https://dokie.li/?style=acm (this stylesheet is currently part of the document, so we can use the value of the title attribute, which is 'acm'. It is equivalent to doing https://dokie.li/?style=https://dokie.li/media/css/acm.css
* https://dokie.li/?style=lncs

**Comment by csarven** [comment]
Chromium is a bit flaky on changing the stylesheet dynamically but it still loads it. Need to go into the dokieli menu and then flip through the stylesheet. Firefox seems okay.
