### ISSUE TITLE
Guide for developers and users

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#169]
The README should include some information to get things started for developers as well as users e.g., how to setup or use dokieli (local/offline, online, extension)

**Comment by bshambaugh** [comment]
I can help with this if you want.

**Comment by boehs** [comment]
Please do

**Comment by milahu** [comment]
still an issue ^^

looking for something like
https://web.hypothes.is/help/embedding-hypothesis-in-websites-and-platforms/
https://h.readthedocs.io/projects/client/en/latest/publishers/embedding/

based on https://dokie.li/docs#html-article ...

### how to embed dokieli in a html document

<details>
<summary>dokieli-example.html</summary>

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>asdf</title>
  <head>
    <link href="https://dokie.li/media/css/basic.css" media="all" rel="stylesheet" title="Basic" />
    <link href="https://dokie.li/media/css/dokieli.css" media="all" rel="stylesheet" />
    <script async src="https://dokie.li/scripts/dokieli.js"></script>
  </head>
  <body about="" typeof="schema:CreativeWork prov:Entity" prefix="rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# rdfs: http://www.w3.org/2000/01/rdf-schema# owl: http://www.w3.org/2002/07/owl# xsd: http://www.w3.org/2001/XMLSchema# rdfa: http://www.w3.org/ns/rdfa# dcterms: http://purl.org/dc/terms/ dctypes: http://purl.org/dc/dcmitype/ foaf: http://xmlns.com/foaf/0.1/ pimspace: http://www.w3.org/ns/pim/space# skos: http://www.w3.org/2004/02/skos/core# prov: http://www.w3.org/ns/prov# mem: http://mementoweb.org/ns# qb: http://purl.org/linked-data/cube# schema: http://schema.org/ void: http://rdfs.org/ns/void# rsa: http://www.w3.org/ns/auth/rsa# cert: http://www.w3.org/ns/auth/cert# wgs: http://www.w3.org/2003/01/geo/wgs84_pos# bibo: http://purl.org/ontology/bibo/ sioc: http://rdfs.org/sioc/ns# doap: http://usefulinc.com/ns/doap# dbr: http://dbpedia.org/resource/ dbp: http://dbpedia.org/property/ sio: http://semanticscience.org/resource/ opmw: http://www.opmw.org/ontology/ deo: http://purl.org/spar/deo/ doco: http://purl.org/spar/doco/ cito: http://purl.org/spar/cito/ fabio: http://purl.org/spar/fabio/ oa: http://www.w3.org/ns/oa# as: https://www.w3.org/ns/activitystreams# ldp: http://www.w3.org/ns/ldp# solid: http://www.w3.org/ns/solid/terms# acl: http://www.w3.org/ns/auth/acl# odrl: http://www.w3.org/ns/odrl/2/ dio: https://w3id.org/dio# rel: https://www.w3.org/ns/iana/link-relations/relation#">
    <main>
      <!-- TODO change the uuid -->
      <article
        about=""
        typeof="schema:Article"
        rel="oa:canonical"
        resource="urn:uuid:48355bb0-0afd-4f73-9a18-f1e8b6fb415b"
        >
        <section>
          hello dokieli
        </section>
        <section>
          how's it going?
        </section>
        <div id="document-license">
          this document is published under the
          <a
            href="https://creativecommons.org/licenses/by/4.0/"
            rel="schema:license"
            title="Creative Commons Attribution 4.0 Unported"
            >CC BY 4.0</a>
          license
        </div>
      </article>
    </main>
  </body>
</html>
```

</details>

... but i dont see the https://dokie.li/docs#user-interface (?)

im trying to use dokieli in "offline mode", so the url is `file:///home/user/dokieli-example.html`

https://dokie.li/#publish says

> Simply add the dokieli CSS and JavaScript to any HTML page to immediately add in-browser editing and annotations.
>
> You can download the dependencies to work offline, or use them directly from [dokie.li](https://dokie.li/). Use in-browser local storage to save your changes or export to save to your harddrive, and to any Web server when you’re ready to share your article.

looks like dokieli only works in online mode for now

**Comment by VirginiaBalseiro** [comment]
Is this resolved?

**Comment by csarven** [comment]
As there is some information now in https://dokie.li/docs , I think we can resolve this issue and focus on specific documentation and implementation improvements in other issues/PRs.

Aside: The user can can edit an HTML document from `file:` to some extent but can't save at that URL. They can export the document and put it up at `https:` somewhere. To go from edit offline (via `file:`) and publish online (via `https:`) we'll need to introduce that feature. Similarly synchronising any changes in the DOM or localStorage while editing at `https:` and using `navigator.onLine` while offline and then later attempting to save the changes once online. (I think most of the functionality is already in place. Probably need to do quick checks... besides actual diff/synchronisation of the data properly by informing the user with potential conflicts etc.)
