### ISSUE TITLE
non-free stylesheet ceur-ws.css

### ISSUE THREAD

**Issue by jonassmedegaard** [dokieli/dokieli#170]
The file media/css/ceur-ws.css contains the following header:

/* THIS STYLE FILE IS FOR EXCLUSIVE USE WITHIN            */
/* CEUR-WS.ORG! DO NOT COPY IT AS A WHOLE OR AS PARTS.    */
/* IN PARTICULAR, THE TAGS CEUR* DEFINED BELOW MAY NOT BE */
/* REUSED OR OVERRIDDEN.                                  */
/* All references to ceur-ws.css in HTML files must be    */
/* relative to ceur-ws.org, e.g. "../ceur-ws.ccs".        */
/* Absolute references like "ceur-ws.org/ceur-ws.css" are */
/* not permitted.                                         */

Seems pretty clearly not-free-for-redistribution to me.

**Comment by csarven** [comment]
Thanks for the issue.

Development moved to https://github.com/ceurws/ceur-make awhile ago and we didn't drop it from here. See also https://github.com/ceurws/ceur-make/blob/dev/dokieli/ceur-ws.css

**Comment by clange** [comment]
Hi, I, technical editor of CEUR-WS.org, confirm that CEUR-WS.org was aware of this development. We moved to the ceurws's repo for further development as @csarven mentioned.
