### ISSUE TITLE
Annotations saved to personal data store do not allow for specified location

### ISSUE THREAD

**Issue by bshambaugh** [dokieli/dokieli#174]
Annotations are saved to the root for my datastore. So for https://bshambaugh.databox.me/profile/card#me all annotations appear as children of  https://bshambaugh.databox.me/ .

Perhaps this should be configurable by the menu (accessed by the hamburger button) on the right. Expect result to be like SaveAs menu.

**Comment by csarven** [comment]
Agreed. The initial design was to keep it simple so it just defaulted to the root. There is an issue which covers this issue https://github.com/linkeddata/dokieli/issues/149 . Would you mind if we close it here and continue the discussion there?

**Comment by bshambaugh** [comment]
No problem. I do the same with my projects.
