### ISSUE TITLE
Error message for CORS issues on open

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#177]
When you try to open a document with dokieli and it can't due to CORS, the UI should make a sad face. And possibly link to instructions about how to fix this at the source, if the user is able to (which they probably aren't) or how to embed dokieli directly into their document at the source domain, if they can't adjust the server settings.

**Comment by csarven** [comment]
Currently if dokieli encounters a server that's not CORS enabled - in practice dokieli sees xhr.status 0 - then it will use its fallback proxy to retrieve the resource.

I'd like to close this issue as it is no longer the case. However, a similar issue can be created to address and show errors/warnings of all 'fetch' related operations.
