### ISSUE TITLE
Explore the generation of PDF from HTML

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#18]
The simplest approach (for most readers) is to print the output to PDF from the Web browser. (Aside: that may or may not be a use-case, but we put that aside for now). However, this currently comes with inconsistent rendering due to different browser engines. Alternative ways to generate the PDF would be using a command-line transformation from HTML.
- Direct transformations from HTML to PDF should be tested
- Transformation from HTML->(La)TeX->PDF should be tested (as the engine and tooling behind (La)TeX to PDF may be more appropriate). Suggested by @kjetilk

**Comment by jodischneider** [comment]
"print" view from http://csarven.ca/dokieli-rww works ok in Chrome, but in Safari it generates a nearly-blank 10-page PDF (which has headers and footers only).

**Comment by csarven** [comment]
I've made a minor update so that the dokieli actually works in Safari (it was apparently not showing before.. and I don't normally test under Safari). This might resolve your issue.

I've checked with Mac OS X 10.8.5, Safari 6.2 (after solving above), and seems to be fine for different views ('csarven' is the default view on that site). You may also want to use other views (see the menu at the top right.. and then the magic-wand icon area with LNCS, ACM etc..). When you click on LNCS for example and if it appears to go back to using browser's default. Switch to another stylesheet and then come back to LNCS. I think that has to do with https://github.com/linkeddata/dokieli/issues/162

**Comment by jodischneider** [comment]
The dokieli "print" button in Safari Version 10.0.3 (12602.4.8) under Mac OS X 10.12.3 (16D32) doesn't work for me currently under any of the 7 stylesheet options. The number of nearly-blank pages does vary depending on the stylesheet, though, so that's something. For #162 I see different behavior on first-click and subsequent-click, but if I stay on a given stylesheet and click the print button multiple times the same length nearly-blank PDF seems to be generated each time.

**Comment by csarven** [comment]
Would you mind checking again preferably in private-window. Is it only the view that appears to be blank or the actual PDF file?

**Comment by jodischneider** [comment]
Both. Screenshot and PDF (from "open in Preview") attached. This is from a private tab in Safari Version 10.0.3 (12602.4.8).

[Decentralised Authoring, Annotations and Notifications for a Read-Write-Web with dokieli.pdf](https://github.com/linkeddata/dokieli/files/868645/Decentralised.Authoring.Annotations.and.Notifications.for.a.Read-Write-Web.with.dokieli.pdf)
<img width="1285" alt="screen shot 2017-03-24 at 12 07 52 pm" src="https://cloud.githubusercontent.com/assets/480102/24305352/a8903126-108a-11e7-89e3-134327c0cfad.png">

**Comment by jodischneider** [comment]
Error persists in Mac Safari Version 10.1.1 (12603.2.4).

**Comment by csarven** [comment]
Closing this issue in favour of https://github.com/linkeddata/dokieli/issues/191 and leaving any print quirks to be addressed through custom stylesheets.
