### ISSUE TITLE
Direct replies to annotations

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#185]
Would be suuuper useful right now. In the way GDocs has it. I realise this might be quite a bit of engineering, but just in case there happens to be a quick fix.. could even do it without notification sending, and only make it available if there's an Annotation Server (not bothering with personal storage)? Or send the notification to the main document, just for the purpose of displaying it, rather than trying to figure out who the author of the annotation is to send a notification to them.

**Comment by csarven** [comment]
Sending the notification to the main article's inbox: 0. Need to consider how discovery works. If the annotation (the one that's being replied to) uses the same inbox as the main article's inbox, that's fine.

At the moment, dokieli doesn't keep track of the notifications it encounters, but only looks for notifications that's about the main article. Created issue #189 . Similarly, main article's annotationService is not directly fetched (only through a notification). Created issue #190 .

Ordered locations to discover and send reply (annotation) to:
* Signed-in user's personal storage (treat this as default canonical - current UI behaviour).
* Annotation's own annotation service (use together with personal storage if available, or as primary - current UI behaviour. Depends on #190 to be useful).
* Article's own annotation service (Depends on #190 to be useful).

Notify (ordered):
* Inbox of the annotation that's being replied to (annotated).
* Inbox of the main article (Depends on #189 to be useful).

**Comment by rhiaro** [comment]
What does 0 mean? No?

If I tweet something, and you reply, then Bob replies to you, I still get a
notification about Bob's reply since i started the thread. That seems
analogous to sending notifications to the main article's inbox, at least as
a fallback to the annotation not having its own inbox.

**Comment by csarven** [comment]
The feature in this issue is now implemented. It works by using annotation's inbox, where the notifications refer to annotations (replies). I've created #275 specifically handle discovery via annotation's annotationService.
