### ISSUE TITLE
[extension] Chrome: extension hides part of the page

### ISSUE THREAD

**Issue by jibe-b** [dokieli/dokieli#209]
Before loading the extension

![image](https://user-images.githubusercontent.com/6146483/28724069-2469e9a4-73b9-11e7-9d56-0a37846b658e.png)

After loading

![screenshot](https://user-images.githubusercontent.com/6146483/28724018-fb139776-73b8-11e7-9388-8a30703c05b0.png)

**Comment by csarven** [comment]
Is that specific to that article or anywhere? What happens when you click back on the article (or close the menu)?

**Comment by jibe-b** [comment]
On most tabs it works pretty fine (thanks a loooot!).

The page above is produces with GWT and I checked another one also done with GWT which breaks.

When I click on the hamburger again, only the gray goes away but the image is still broken.

On http://ncase.me/trust/ it breaks part of the animation too.

**Comment by csarven** [comment]
The animation seems to work fine for me now. Can you confirm?

Keep in mind that the extension is not bullet-proof. There are many arbitrary things can go on a webpage, it is not guaranteed to be always functional - at least without changing the core architecture.
