### ISSUE TITLE
Note taking

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#21]
Implement a note taking feature. Suggested by @clange . See also http://en.wikipedia.org/wiki/Org-mode

**Comment by olberger** [comment]
I'm not sure about the expressed need: could you clarify ?

**Comment by olberger** [comment]
I'd be interested in authoring with org-mode some papers embedding meta-data, but I'm not sure, this is the same need, even if the outcome could be identical ;-)

**Comment by clange** [comment]
I don't remember what exactly I had suggested back then. I think that when I saw how LR displays the table of contents of a paper, I was reminded of org-mode, and then I was reminded that one can use org-mode as a format-independent way of writing scientific papers (exporting to HTML, LaTeX, etc.).

**Comment by csarven** [comment]
Perhaps it is safe to say that this issue is out of the scope of LR. If there are implementations which generate output towards LR, or use LR as input, that's always welcome and can be referred to from this project.

As a side "note" (no pun intended), note taking would be something that's part of annotations in general. There is no issue for this yet, but I would say that it is a better fit in that context.
