### ISSUE TITLE
Copying and Pasting RDF-Turtle into "Embed Data" control UI

### ISSUE THREAD

**Issue by kidehen** [dokieli/dokieli#218]
@csarven, 

Attempt to copy and paste the following, from [this post](http://ontology2.com/notebooks/local/Inference_Over_RDF_Containers.html), into the "Embed Data" control UI .

```@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix : <http://example.com/> .

:tioga_downs_2017_08_14 
    a rdf:Seq ;          
    rdf:_1 :race_1 ;                
    rdf:_2 :race_2 ;                
    rdf:_3 :race_3 .                
                                    
:race_1 
    a rdf:Seq ;
    rdf:_1 "PRINCE ADIRAN" ;        
    rdf:_2 "KDMAKEWAY" ;            
    rdf:_3 "ANDERSON VALLEY" ;      
    rdf:_4 "SETTINEMONFIRE" ;       
    rdf:_5 "TRILLIONAIR" ;          
    rdf:_6 "OZZY BLUE CHIP" .       
                                    
:race_2 
    a rdf:Seq ;                            
    rdf:_1 "MACHMEMACKIE" ;         
    rdf:_2 "FREE LOVE" ;            
    rdf:_3 "FRANKIES DRAGON" ;      
    rdf:_4 "IM AN ART MAJOR" ;      
    rdf:_5 "GOLD STAR SPIKE" ;      
    rdf:_6 "F TWENTY TWO" ;         
    rdf:_7 "TAILGUNNER HANOVER".    
                                    
:race_3 ; 
    a rdf:Seq ;                           
    rdf:_1 "LYONS JOHNNY" ;         
    rdf:_2 "BETTORSLUCKYSTREAK" ;   
    rdf:_3 "DASH OF DANGER" ;       
    rdf:_4 "NEPTUNE" ;               
    rdf:_5 "WINYARD HANOVER" ;       
    rdf:_6 "DEE'S ROCKETMAN" .                                           
""")
```
Issue:
It isn't possible using the version in the Chrome Store. It works fine using our [dokieli extension fork](https://github.com/OpenLinkSoftware/dokieli).

**Comment by csarven** [comment]
Reading this issue alone, it is not clear what's "isn't possible" exactly or at what part of the process.

I presume you are relating it to https://github.com/linkeddata/dokieli/pull/217 . I've tested based on my change request at https://github.com/linkeddata/dokieli/pull/217#pullrequestreview-62818832 and it works in Chrome extension.

Once that gets merged, this issue should be resolved, and I'll update the store.

**Comment by csarven** [comment]
Or is this literally about the "paste" problem? I've encountered that with the keyboard `ctrl+v`. Bringing up the right-click menu and then *Paste* works. In any case, that's not specific to the Chrome extension, it persists in Chrome. Firefox is okay.

**Comment by kidehen** [comment]
I can even repeat the problem using this document:

1. Copy the sample Turtle to my clipboard

1. Initialize dokie.li extension

1. Open "Embed Data" control

1. Attempt to paste in Turtle using CTRL+V pattern .

Note, I only have this problem when I use the CTRL+V pattern i.e., Menu | Paste works. 

CTRL == Command button on Mac OS X (my default platform).

**Comment by csarven** [comment]
Yes, I can confirm the <kbd>CTRL-V</kbd> issue. MediumEditor related. The issue occurs in regular (non-extension) mode as well.

**Comment by kidehen** [comment]
Note, our dokie.li fork doesn't exhibit this problem.

**Comment by csarven** [comment]
This issue is resolved AFAIK. Sort of bypassed it by making the MediumEditor's editable area to not include the containers with form inputs for pasting. See also https://gitter.im/linkeddata/dokieli?at=5a4a5dbf0163b028109dd126
