### ISSUE TITLE
dokieli Menu loses event listener after going into Edit mode in Web Extension

### ISSUE THREAD

**Issue by kidehen** [dokieli/dokieli#219]
@csarven,

Here's a usage sequence that works fine with our dokie.li extension, but not with the edition published to the Chrome Store:

1. goto: http://ontology2.com/notebooks/local/RDFContainers.html

2. Click on dokie.li ext icon

3. Click on “Edit” control from dokie.li menu

4. Click on Hamburger icon (re. dokie.li menu) --- no response. 

@smalinin will prepare a pull-request, when he gets a moment.

**Comment by csarven** [comment]
I can confirm the issue in Chromium and Firefox, and only occurs in browser extension.

**Comment by csarven** [comment]
IIRC, MediumEditor drops the events on the container it is active on. Related issue: https://gitter.im/yabwe/medium-editor?at=5993fa09c101bc4e3a21cfc3
