### ISSUE TITLE
[ScienceFairApp] provide a JATS feed to make dokieli a source to the ScienceFairApp

### ISSUE THREAD

**Issue by jibe-b** [dokieli/dokieli#229]
ScienceFairApp is build on dat https://github.com/datproject/dat and could be a way to make linkedresearch publications more visible.

I let you have a look to:

https://github.com/codeforscience/sciencefair#secure-flexible-distributed-datasources

**Comment by michael** [comment]
I'm one of the original developers behind eLife Lens (which is used as the article viewer in ScienceFair). Right now we are working on a set of tools related to authoring JATS-XML documents in a visual, word-processor like interface. Maybe this work is relevant to your project. See #237

**Comment by csarven** [comment]
Decided to skip on this feature for the foreseeable future.
