### ISSUE TITLE
[extension] Firefox WebExtension link in README.md is broken

### ISSUE THREAD

**Issue by vhfmag** [dokieli/dokieli#231]
The [Firefox WebExtension's page](https://addons.mozilla.org/en-US/firefox/addon/dokieli/) can't be found. I couldn't find it by directly searching for dokieli, either. Is it just me?

**Comment by csarven** [comment]
Thanks for noticing that. The URL was correct, but it happened to be that the version at the time didn't pass all the requirements to be published at addons.mozilla.org, so it was taken down.

When we address those issues - mostly minor - and try to publish again, and gets a thumbs up from the reviewers, it'll be there again. We could of course regularly push a new version to mozilla, but I didn't want to bother until we resolve the actual requirements.

Does this response adequately address your issue?

If you want to experiment with the extension, simply import the cloned directory in addons (debugging mode and as temporary). See also http://dokie.li/docs#web-extension

**Comment by vhfmag** [comment]
Yes it does, thanks! I'll keep a look for when the extension is released again.

**Comment by cerisara** [comment]
As there aren't news about it 12 months later, may be it is best for now to just replace the link in the README.md to rather point to http://dokie.li/docs#web-extension ?

**Comment by csarven** [comment]
@cerisara Updated. Thanks.
