### ISSUE TITLE
"npm run build"  => error

### ISSUE THREAD

**Issue by dr0i** [dokieli/dokieli#232]
`$ npm run build`
> 0 info it worked if it ends with ok
> 1 verbose cli [ '~/.nvm/versions/node/v9.5.0/bin/node',
> 1 verbose cli   '~/.nvm/versions/node/v9.5.0/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'build-dist' ]
> 2 info using npm@5.6.0
> 3 info using node@v9.5.0
> 4 verbose run-script [ 'prebuild-dist', 'build-dist', 'postbuild-dist' ]
> 5 info lifecycle dokieli@0.3.8~prebuild-dist: dokieli@0.3.8
> 6 info lifecycle dokieli@0.3.8~build-dist: dokieli@0.3.8
> 7 verbose lifecycle dokieli@0.3.8~build-dist: unsafe-perm in lifecycle true
> 8 verbose lifecycle dokieli@0.3.8~build-dist: PATH: ~.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:~/git/dokieli/node_modules/.bin...
> 9 verbose lifecycle dokieli@0.3.8~build-dist: CWD: ~/git/dokieli
> 10 silly lifecycle dokieli@0.3.8~build-dist: Args: [ '-c', 'webpack --progress --colors' ]
> 11 info lifecycle dokieli@0.3.8~build-dist: Failed to exec build-dist script
> 12 verbose stack Error: dokieli@0.3.8 build-dist: `webpack --progress --colors`
> 12 verbose stack spawn ENOENT
> 12 verbose stack     at ChildProcess.<anonymous> (~/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
> 12 verbose stack     at ChildProcess.emit (events.js:160:13)
> 12 verbose stack     at maybeClose (internal/child_process.js:943:16)
> 12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> 13 verbose pkgid dokieli@0.3.8
> 14 verbose cwd ~/git/dokieli
> 15 verbose Linux 4.14.0-2-amd64
> 16 verbose argv "~/.nvm/versions/node/v9.5.0/bin/node" "~/.nvm/versions/node/v9.5.0/bin/npm" "run" "build-dist"
> 17 verbose node v9.5.0
> 18 verbose npm  v5.6.0
> 19 error file sh
> 20 error code ELIFECYCLE
> 21 error errno ENOENT
> 22 error syscall spawn
> 23 error dokieli@0.3.8 build-dist: `webpack --progress --colors`
> 23 error spawn ENOENT
> 24 error Failed at the dokieli@0.3.8 build-dist script.
> 24 error This is probably not a problem with npm. There is likely additional logging output above.
> 25 verbose exit [ 1, true ]

**Comment by csarven** [comment]
Did you run `npm install` before that?

**Comment by akuckartz** [comment]
I just tried
> npm run build

on Debian and it turned out that webpack was missing.

Installing webpack helped to resolve this.

**Comment by dr0i** [comment]
@csarven uh, yes, a simple `npm install` as prerequisite did the job. Well sorry for this beginners problems... Nevertheless, I opened a PR to reflect this in the README.
