### ISSUE TITLE
Remember annotation storage choice

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#233]
I keep choosing 'annotation service' but when I make a new annotation it's switched back to the default 'personal storage' option. Just need to remember for the current session, at least.

**Comment by csarven** [comment]
Not a "bug" I think but yea, I totally agree. Something that was *bugging* me as well.

Introduced `DO.C.User.UI` to keep track of this sort of stuff in memory. Starts tracking after submitting the annotation. The states are lost after refresh.
