### ISSUE TITLE
Use Node dependencies for Medium Editor (Tables) and SimpleRDF

### ISSUE THREAD

**Issue by bencomp** [dokieli/dokieli#240]
Following the discussion in #239 and #231, one of the apparently major issues for not allowing dokieli in the Firefox addons 'market' is that the extension code contains minified JavaScript. It looks like the included `scripts/medium-editor.min.js`, `scripts/medium-editor-tables.min.js` and `scripts/simplerdf.js` are minified.

These are available as NPM packages:

- [simplerdf](https://www.npmjs.com/package/simplerdf)
- [medium-editor](https://www.npmjs.com/package/medium-editor)
- [medium-editor-tables](https://www.npmjs.com/package/medium-editor-tables)

I just recently started exploring the (Node)JS world and the WebExtensions world, but perhaps depending on these packages in package.json instead of including them as minified code directly can help get dokieli back in [AMO](https://addons.mozilla.org/).

**Comment by csarven** [comment]
Maybe we should put this in motion along with the plan to having a single `do.js` for distribution.

As for the minification process, are you suggesting that we use a non-minified version for Web Extension and minified for the general distribution or alternative approach?

/me pokes @dmitrizagidulin for ideas on general package.json planning.

**Comment by bencomp** [comment]
Well, I'm guessing that Mozilla may already know about the source code for the libraries included as dependencies, or that they have another way of checking the source code for libraries.

If the included build instructions produce the exact same code (minified or not) as the uploaded XPI **and** the provided source code only contains dokieli-specific JS and references to common JS libraries, that may be enough to pass the AMO checks.

Mozilla say that for Web Extensions you don't need to minify code as it will not improve performance. But from the comments you included in https://github.com/linkeddata/dokieli/issues/239#issuecomment-388693838, it looks like allowing Mozilla to check the source and build result is more important than actually using non-minified code in the extension.

I can give it a shot and see if I really (start to) understand building/using NPM packages :)

**Comment by bencomp** [comment]
A drawback of the removing the extra .js files from scripts is that getting started from this git repository will take extra steps. After cloning the repository you cannot just open index.html in a browser, because it currently tries to load the scripts directly.

Instead of putting the minified libraries in the repository, you (or we :)) can use GitHub releases to distribute a 'ready to go' zip file.

**Comment by csarven** [comment]
I think we need to compare the regular and minified sizes - at the moment, only some of the JS is minified (as you know). I prefer that what's used on webpages is the minified version (also what's served from dokie.li ), and that the Web Extension version can be regular - this is something that can be generated with the build command. The repository doesn't have to ship with the regular version.

**Comment by bencomp** [comment]
This seems to work: https://github.com/bencomp/dokieli/tree/240-npm-dependencies

```bash
npm install
npm run build-simplerdf
npm run copy-medium-editor
```

Then you should have all files in `scripts/` that are expected by the `index.html` and `manifest.json` files.

**Comment by csarven** [comment]
This is great, thanks!

Just to be clear on the goal: dokieli will eventually only ship `scripts/do.js` and no install/build required after cloning the repository. Of course rebuilding is still required for development but that stuff will be derived from what's in `src/`.

Is that what you're driving towards in your fork?

As first step (PR): what comes out of the box (ie. just cloning the repository) should work without getting npm involved, so can we stick to shipping the distribution files in `scripts/`. So, okay to move the simplerdf and medium-editor stuff into src, and just copy them into `scripts/` as you're doing with build-simplerdf and copy-medium-editor (but it'd be great if that copying can be tucked under npm install - makes sense?)

Second:
When all of the JS can be included in scripts/do.js for distribution, then we can of course drop the rest of the scripts/*.js

**Comment by bencomp** [comment]
My fork as a whole is meant to help dokieli development in whatever small or large way ;)
This branch is a small step in my learning about JavaScript and helping a bit to get the Firefox extension back in AMO.

I understand that you want to have the complete package in the git repository, no install needed, but this is different than for most open-source projects. Since this is your project, I'll add the 'built' simplerdf and medium-editor back to `scripts/` (rather than `src/`, so that it's clear that `src` is, well, the source and that `scripts` contains the output).

> but it'd be great if that copying can be tucked under npm install - makes sense?

AFAIK `npm install` doesn't build the files to make them ready for distribution, it only gets dependencies and puts them in `node_modules/`. It woud be better to add this as a step of `npm run build`, wouldn't it?

I'll open a PR with the changes.

**Comment by csarven** [comment]
I *really* appreciate you taking on this task. I think it is on a really good track.

Yea, as first step, I think it is okay to keep those scripts in `scripts/` as is. Only for the second phase where we have a single JS (do.js) which includes all of the other scripts, we can then have the scripts in `src/`. So, we'll probably just have `scripts/do.js` in the end, and everything else in `src/`. As to whether simplerdf and medium-editor etc are built separately and then copied to `src/` or being compiled into do.js through npm run build, that can however works best. You're right I was mistaken re `npm install` - as a step of `npm run build` sounds good.


I'd like to push it as *our* project as much possible. Historically the idea was to always lower the barrier for people to use it and get involved eg. some may use the Web interface to spawn their own dokieli copy, whereas others may just want to clone the repository and go. There shouldn't be an explicit need for "installation". The intention is not to be like most open source software - if they indeed require several steps to get going. Beyond the basics like above, setup/configuration/installation should be left for those that want to work / develop dokieli. Hence, it'd be great if we can separate these as much as possible. I'm open to alternative approaches if there are technical or social reasons preventing us from taking this as a base "rule".

**Comment by csarven** [comment]
Thanks for kicking this off.

The master branch now includes a do.js (minified) that is derived from packages.json and src/*.js. We can of course have/think about both (un)minified part of the repository, and the extension can use either (eg. if AMO prefers unminified for do.js, that's all fine).

Does AMO actually require that all the source of the dependencies mentioned in package.json need to be part of the extension build/source? I'm guessing that the unminified do.js (which includes all the dependencies) should be sufficient, but this needs to be confirmed.

**Comment by csarven** [comment]
Using Node dependencies now for ME but not SimpleRDF. SimpleRDF has to stay that way for now any way - SimpleRDF won't be used in the near future - until dokieli uses another RDF library - which is hopefully around the corner. So, closing this / won't fix.
