### ISSUE TITLE
login not working on Win 8

### ISSUE THREAD

**Issue by mrchristian** [dokieli/dokieli#246]
Hi,

My login works on Ubuntu, but not Win 8. Tried twice several hours apart. The OSs are on different machines.

Simon

Details

Win 8

https://mrchristian.solid.community/profile/card#me

Dokieli
Version
0.3.15

Google Chrome is up to date
Version 68.0.3440.84 (Official Build) (64-bit)

OS Name	Microsoft Windows 8.1 Pro
Version	6.3.9600 Build 9600

##############################################

Ubuntu

https://mrchristian.solid.community/profile/card#me

Dokieli
Version
0.3.15

Chromium
Version 66.0.3359.139 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

LSB Version:
core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

**Comment by csarven** [comment]
Thanks for the report. I've checked with Windows 8 but wasn't able to reproduce. Would you mind repeating this with the Web/Developer inspector open? The Console and Network tabs should reveal something.

**Comment by csarven** [comment]
This issue is based on the browser extension available from the Chrome store right? I'm going to push a minor update (make sure it is version 0.3.16) and see if that resolves it.

**Comment by csarven** [comment]
Can't replicate and this is million years old issue :) Let's revisit if needed =)
