### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by crackcomm** [dokieli/dokieli#260]
I would like to try dokieli, are you planning on releasing a working version?

**Comment by csarven** [comment]
Yes, it goes without saying re "stable release". What's currently in the repo is "working". If you have specific criteria, it'd be good to know. Would you like to expedite releases by chipping in with the issues eg. resolving https://github.com/linkeddata/dokieli/commit/c0aa325c5654a2622cdd4975197e520d0bce82f8#commitcomment-31254851 ?

If you'd like to discuss further, you're welcome to join the chat at https://gitter.com/linkeddata/dokieli . I hope you don't mind me closing this issue.

**Comment by crackcomm** [comment]
The criteria would be to work as described in https://github.com/linkeddata/dokieli#development

**Comment by crackcomm** [comment]
I'd love to resolve the issues, I have no idea what do you want to import by saying './simplerdf.js' which is not existent file.

**Comment by csarven** [comment]
Thanks for the notice. Apparently I didn't push that in. Now in: https://github.com/linkeddata/dokieli/commit/3175ce3982a635f7f0588f1989922f4affed9e4c .

**Comment by crackcomm** [comment]
Amazing, I thought the posted error had enough data.

Now it rendered.

Save says saved but doesn't save, does it work in local storage or not?

Here is my console:

```
utils-browser.js:47 GET http://localhost:5000/inbox/ 404 (Not Found)
(anonymous) @ utils-browser.js:47
window.DO.utils.defaultRequest @ utils-browser.js:15
(anonymous) @ lite.js:92
window.DO.LdpStore.graph @ lite.js:88
get @ index.js:45
getGraph @ graph.js:18
getNotifications @ dokieli.js:105
showNotificationSources @ dokieli.js:149
(anonymous) @ dokieli.js:138
(anonymous) @ dokieli.js:137
Promise.then (async)
showInboxNotifications @ dokieli.js:135
init @ config.js:22
(anonymous) @ dokieli.js:7308
dokieli.js:127 status code error: 404
4:5000/#personal-storage:1 Unsafe attempt to load URL https://dokie.li/media/track/dokieli.vtt from frame with URL http://localhost:5000/#personal-storage. Domains, protocols and ports must match.

dokieli.js:151 Uncaught (in promise) TypeError: i.forEach is not a function
    at dokieli.js:151
(anonymous) @ dokieli.js:151
Promise.then (async)
showNotificationSources @ dokieli.js:149
(anonymous) @ dokieli.js:138
(anonymous) @ dokieli.js:137
Promise.then (async)
showInboxNotifications @ dokieli.js:135
init @ config.js:22
(anonymous) @ dokieli.js:7308
```

**Comment by csarven** [comment]
Not so amazing. I suppose it did but I didn't see it. My mind glossed over to the possibility of being a Windows path issue. Assumed simplerdf.js was already in place... 

The errors you've posted above are unlikely to be related to your issue. Definitely something that should be handled better.

Can you elaborate on your exact steps? I'm assuming that you have dokieli at http://localhost:5000/ and you've hit 'Save'?

Please note that the general approach was to progressively enhance.. so some things may not fully work on "local".. (eg if dokieli is loaded from `file:`). If the server you are running at welcomes HTTP PUT (in this example with 'Save') and your access controls check out, then it should work. So, I'm curious to know what your setup is like. IIRC, there was some work to disable the Save,.. but I can definitely look into that again. If the server doesn't signal anything in particular about the current user's rights on the requested resource, then dokieli can't particularly tell if it can Save to that location or not. So, at the moment, the default is to let the user press (not bullet proof...).
