### ISSUE TITLE
The name of a new document cannot be chosen

### ISSUE THREAD

**Issue by bourgeoa** [dokieli/dokieli#272]
The name of a **create** or **save as**  document cannot be chosen can it be improved ?

The creation process is different from the Solid one : 
- creation of a file
- in solid a folder and an index.html file

Is there a reason not to be consistant and it is not easy to make some versioning

**Comment by csarven** [comment]
How can it not be chosen? If the user is signed-in, dokieli even shows the user's storage when creating a new document or doing a save as, let's the user choose the directory/container to save to (or a resource to overwrite to). It also let's the user specify the filename. That is pretty much how most common software work for saving a document.

What other applications do don't have to be the same. If the solid-panes application let's the user give an input and then turn that into a {input}/index.html pattern, that's its decision. Nothing wrong with that. Note that, that particular process is outside the scope of dokieli.

I propose to close this issue.

**Comment by bourgeoa** [comment]
It seems I mis-used the function. I succed now to create the name of the file
