### ISSUE TITLE
Attempt to save home page of dokieli fails: "Unable to save: you are not authorized."

### ISSUE THREAD

**Issue by mauricew9** [dokieli/dokieli#274]
Followed these steps (Firefox). "xxxx" below is a placeholder for the real username.

1. Create new POD/Web ID in Solid Community:  https://xxxx.solid.community/profile/card#me
2. Verify that I can log in with new Web ID to browse /public folder. Access options say my user has fulll access to /public.
3. Browse to https://dokie.li/
4. Click button at upper-right of the page to access available options, click Sign In
5. Enter web ID https://xxxx.solid.community/profile/card#me, click Sign In
6. Upper right panel now shows the name from my profile, and the live-long-and-prosper sign-out icon
7. Click Save As in upper-right panel
8. Dialog appears; enter https://xxxx.solid.community/public/aaa
9. Click Save
10. Receive error in red text at bottom of pop-up: "Unable to save: you are not authorized."

The Save request issued from the browser (PUT https://xxxx.solid.community/public/aaa HTTP/1.1):

> Host: xxxx.solid.community
> User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
> Accept: */*
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate, br
> Referer: https://dokie.li/
> content-type: text/html; charset=utf-8
> link: <http://www.w3.org/ns/ldp#Resource>; rel="type"
> origin: https://dokie.li
> Content-Length: 21432
> Connection: keep-alive
> Cookie: connect.sid=s%3AoBhBeEpJvnL8H1L0RNvHoxffKVo5KGe-.Tx5mJ8%2FxAk3Y%2BdHRr391ffeLkVk3FAsjB3%2F8p9LJYCk

The response:

> HTTP/1.1 401 Unauthorized
> X-Powered-By: solid-server
> Access-Control-Allow-Origin: https://dokie.li
> Vary: Accept, Authorization, Origin
> Access-Control-Allow-Credentials: true
> Access-Control-Expose-Headers: Authorization, User, Location, Link, Vary, Last-Modified, ETag, Accept-Patch, Accept-Post, Updates-Via, Allow, WAC-Allow, Content-Length, WWW-Authenticate
> Allow: OPTIONS, HEAD, GET, PATCH, POST, PUT, DELETE
> Link: <aaa.acl>; rel="acl", <aaa.meta>; rel="describedBy", <http://www.w3.org/ns/ldp#Resource>; rel="type"
> WWW-Authenticate: Bearer realm="https://solid.community", scope="openid webid"
> Content-Type: text/html; charset=utf-8
> Content-Length: 1616
> ETag: W/"650-H6CBYFLp0quydxTXIR4USsOoJ50"
> set-cookie: connect.sid=s%3AoBhBeEpJvnL8H1L0RNvHoxffKVo5KGe-.Tx5mJ8%2FxAk3Y%2BdHRr391ffeLkVk3FAsjB3%2F8p9LJYCk; Domain=.solid.community; Path=/; Expires=Fri, 21 Dec 2018 21:34:04 GMT; HttpOnly; Secure
> Date: Thu, 20 Dec 2018 21:34:04 GMT
> Connection: keep-alive

The content of the response appears to be a webpage that is intended to appear as a pop-up to prompt for credentials:

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Log in</title>
  <link rel="stylesheet" href="/common/css/bootstrap.min.css">
  <link rel="stylesheet" href="/common/css/solid.css">
</head>
<body>
<div class="container">
  <div class="page-header">
    <div class="pull-right">
      <button class="btn btn-primary" onclick="register()">Register</button>
      <button class="btn btn-success" onclick="login()">Log in</button>
    </div>
    <h1>Log in to access this resource</h1>
  </div>

  <div class="alert alert-danger">
    <p>
      The resource you are trying to access
      (<code>https://xxxx.solid.community/public/aaa</code>)
      requires you to log in.
    </p>
  </div>

</div>
</div>
<script src="/common/js/solid-auth-client.bundle.js"></script>
<script>
  async function login () {
    const session = await solid.auth.popupLogin()
    if (session) {
      // Make authenticated request to the server to establish a session cookie
      const {status} = await solid.auth.fetch(location)
      if (status === 401) {
        alert(`Invalid login.\n\nDid you set ${session.idp} as your OIDC provider in your profile ${session.webId}?`)
        await solid.auth.logout()
      }
      // Now that we have a cookie, reload to display the authenticated page
      location.reload()
    }
  }

  function register () {
    const registration = new URL('/register', location)
    registration.searchParams.set('returnToUrl', location)
    location.href = registration
  }
</script>
</body>
</html>
```

**Comment by csarven** [comment]
Thank you for reporting this. I think I see what may have gone wrong, and we should improve the UI.

As the WebID you've obtained under xxxx.solid.community, that dataspace will use WebID-OIDC authorization. What you've entered in dokieli's Sign In uses WebID-TLS based authorization. If you could try to click the Sign In button beside "or with OpenID Connect", that should trigger a popup where you can select your Identity Provider (Solid Community for you in this case). The rest of the workflow should be the same.

Please let me know if that works out.

Going forward, we'll have a single input for WebID to handle both TLS and OIDC options..

**Comment by mauricew9** [comment]
Thank you, that worked!
