### ISSUE TITLE
"TypeError: e is null" when placing a comment

### ISSUE THREAD

**Issue by RubenVerborgh** [dokieli/dokieli#290]
- I go to https://timbl.com/timbl/Public/Test/2018/Cascade%20test/Dokieli%20tests/Dashboard%20ideas.html
- I am logged in
- I try to save a comment

```
TypeError: e is null2 doc.js:311
    getNodeLanguage doc.js:311
    completeFormSave dokieli.js:7761
    doFormSave dokieli.js:7604
    handleSaveClick dokieli.js:8516
    handleSaveClick self-hosted:1003
```

corresponding to

```
function getNodeLanguage(node) {
  var lang = '';
  var closestLang = node.closest('[lang]');  // <<< so looks like node is null
  if (closestLang) {
    lang = closestLang.getAttribute('lang');
  }
```

**Comment by csarven** [comment]
Thanks. Fixed.

Just out of curiosity, were you doing an internal "comment" (while in Edit mode)?

**Comment by RubenVerborgh** [comment]
Thanks. I was in reading mode.

**Comment by csarven** [comment]
Ok, you may want to know this any way:

re "Reading mode", in that case, that was probably an annotation with "replying" motivation. That's supposed to get saved to your storage. And it will only appear in the document again if notifications are involved.. or through "Activities" (in menu).

What I meant by internal (Edit -> "note" button after selecting) is that it gets injected into the document as "commenting" motivation. The document needs to be saved in order to persist those kinds of annotations.

**Comment by RubenVerborgh** [comment]
Ah yes, was my storage. I take it timbl.com is not using a live version? Otherwise I can retry.

**Comment by csarven** [comment]
That document doesn't have an inbox, so if the annotation got saved on your storage, it is potentially reachable from https://drive.verborgh.org/ . It may be a flaky but after sign-in, click on "Activities" - that tries to load annotations that you and your contacts made on this document (via what's accessible from pim:storage, as:outbox)

**Comment by RubenVerborgh** [comment]
Where on https://drive.verborgh.org/ would you expect it? I don't see it in /public/.

**Comment by csarven** [comment]
Wherever the annotation got saved to.. probably at `/{uuid}`? Activities only looks at `/` and the resources linked from `ldp:contains`, `as:items`, `as:orderedItems`. It doesn't currently follow containers or other collections. Maybe it should? Kinda decided against in the initial design - wanted to keep it light for now while we understand this better. We can move this to a separate issue...

**Comment by RubenVerborgh** [comment]
> Wherever the annotation got saved to.. probably at `/{uuid}`?

Checked, nothing there.

Should I BTW have my pim:storage set to something like `/public/`? [Currently at `/`.](http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F%23me&query=PREFIX%20pim%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fpim%2Fspace%23%3E%0ASELECT%20%3Fstorage%20WHERE%20%7B%0A%20%20%3Chttps%3A%2F%2Fruben.verborgh.org%2Fprofile%2F%23me%3E%20pim%3Astorage%20%3Fstorage.%0A%7D)
