### ISSUE TITLE
Locked out / issues with document after source edit

### ISSUE THREAD

**Issue by justinwb** [dokieli/dokieli#293]
Note that this may only be happening on NSS, or maybe is because of / exacerbated by NSS. 

I was working on a dokieli document on inrupt.net (running NSS 5.1.4), and then brought up a source view to hand edit something (in this case I just removed some <span>s). When i clicked update on the source edit - it ended up locking me out. Any requests for the document resource were just hanging. 

It turns out that there was a lock file created by nss to protect against resource contention that wasn’t getting released. once i manually removed it, I was able to bring the document up again. When the document was brought back up, I don't seem to be able to get back into edit mode (or perform other actions from the menu) though.

**Comment by csarven** [comment]
It seems that the document somehow got mangled in that lock phase. I would love to be able to reproduce. How does a lock happen in NSS? Or was it the OS/filesystem?

Note that dokieli's Source->Update only updates the DOM state, and so no write request is made to the server (aside: perhaps it should but that's a separate issue). Only when a write operation (eg. "Save") is made something gets committed which would explain the DOM being in a weird state. It is still a bit weird in that the dynamically added nodes by dokieli is omitted (there is a normalisation step) before the HTTP write.
