### ISSUE TITLE
`pre` normalisation and serialisation

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#294]
`pre` normalisation needs to be better / fix issues. Generally, leave `pre`'s value alone - don't process eg:

* don't process HTML entities
* whitespace / new lines stay as is

**Comment by brownhoward** [comment]
By way of an example of this, if you enter the following source:
```<p>For example, the following code snippet references the UI Ontology and the RDF syntax in the Form Model.</p>
<pre>@prefix ui:&lt;http://www.w3.org/ns/ui#&gt; .
@prefix rdf: &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt;</pre>
```

you get the following display rendered:
![Screen Shot 2019-09-16 at 12 09 36](https://user-images.githubusercontent.com/45850928/64974677-4911ef80-d87b-11e9-921d-ddcdcc6a6a0f.png)

If you then save the document, the display changes to:
![Screen Shot 2019-09-16 at 12 14 23](https://user-images.githubusercontent.com/45850928/64974868-b6be1b80-d87b-11e9-861f-12e587b74742.png)

and the source to:
```<p>For example, the following code snippet references the UI Ontology and the RDF syntax in the Form Model.</p>
<pre>@prefix ui:<http: ns="" ui#="" www.w3.org=""> .
@prefix rdf: <http: 22-rdf-syntax-ns#="" www.w3.org=""> .</http:></http:></pre>
```

**Comment by csarven** [comment]
Fixed to the best of my knowledge but please do let me know if you encounter anything weird. Until we have a test for normalisation.. this will have to do :)

Thanks for reporting this. It has been bothering me for a long time. I couldn't resolve it in the past every time I looked at it. Lesson: fix issues a few years later with fresh eyes.
