### ISSUE TITLE
Using Dokieli in Solid data browser, strange behaviour

### ISSUE THREAD

**Issue by Okilele-newbie** [dokieli/dokieli#297]
I don’t understand how to use Dokieli.
I found and used some features (set author, invite people etc…) but I still don’t get the editor pane and I am unable to enter text.
More of this as I created a Dokieli named “TestDoc” I find it in the folder of my pod as TestDoc.html, this is ok, but if I am back to it the “html” extension disappear.
And then appears a new item named “edu.mit.solid.pane.Dokieli” which is also a Dokeli document …
So : Am I dummy or is there some bugs ?

**Comment by csarven** [comment]
>I found and used some features (set author, invite people etc…) but I still don’t get the editor pane and I am unable to enter text.

I think that's a duplicate of https://github.com/linkeddata/dokieli/issues/271 or https://github.com/linkeddata/dokieli/issues/203 . If so, can we close this issue?

>More of this as I created a Dokieli named “TestDoc” I find it in the folder of my pod as TestDoc.html, this is ok, but if I am back to it the “html” extension disappear.
>And then appears a new item named “edu.mit.solid.pane.Dokieli” which is also a Dokeli document …

That interaction and behaviour is out of scope for dokieli. It is part of data-browser ( https://github.com/solid/mashlib ).

**Comment by megoth** [comment]
Maybe we can move this issue to [solid-panes](https://github.com/solid/solid-panes) if #203 or #271 addresses the other problem, and then I can work on the data browser issue there?

**Comment by csarven** [comment]
That'd be great, thanks! Just would like confirmation from @Okilele-newbie re duplicate.

**Comment by Okilele-newbie** [comment]
Hi,
I don't think those are the same.
I guess - but I am not sure - that opening a Dokieli I should see some kind
of editor pane (with bold, insert image, insert tools link etc...) but I
see ... nothing.
May be this is also caused by the mashlib integration.
And also I don't care, this was for le only a test and I don't plan to
really use it.

Thanks and regards
Bruno

Le ven. 22 nov. 2019 à 13:26, Sarven Capadisli <notifications@github.com> a
écrit :

**Comment by csarven** [comment]
While in 'Edit' mode (activate it from the dokieli menu), select some text. It should popup a toolbar with document formatting features.

**Comment by Okilele-newbie** [comment]
Hello,

I tried to do as you explained (...select some text. It should popup a
toolbar...) and no toolbar did popup. I also tried the Reply action on the
menu and got messages as those :

Need a note and a location to save it.

We could not notify the author of your reply:Could not determine the author
inbox endpoint

Actually I dont write you to be able to used Dokieli, I am not involved in
any community that should use it, but to remind you today applications must
be - as good code - self explaining. And if this not the case users won't
use it.
So if you want to go ahead writing a - maybe - good application don't
change anything. But if you would like people use it make it usable.

Hope it helps
Bruno.

Le sam. 23 nov. 2019 à 14:37, Sarven Capadisli <notifications@github.com> a
écrit :

**Comment by brownhoward** [comment]
Dokieli does have some quirks, but it does make for a decent document editor within the Solid environment. I have occasionally seen an issue entering text on a newly created Dokieli doc, but there is an easy workaround:
1. Create a new Dokieli doc making sure to include a .html extension.
2. Display the source for the new document.
3. Enter some random text in the <article> element of the source:
```
<main>
  <article about="" typeof="schema:Article">
    <h1>test</h1>
    Some Random Text
  </article>
</main>
```
4. Click 'Update' to update the source for the Dokieli doc.
5. 'Save' the doc.

You should now be able to now edit the document via the editor.

As for viewing the pop-up, if you highlight a single line of text, you should see the black pop-up.

**Comment by Okilele-newbie** [comment]
Hello,

thank you, I was now able ti use it.
But my las post - I apologize if it was a bit rough - was not mainly about
the way to use it but about the pleasure we have using it, which is null.
You should think your app as a game and make users enjoy using it as they
enjoy using Call Of Duty or Sims or any other game.
As an exmple have a look at Slack which is my day to day tool (and maybe
yours also ...)

Regards and good luck
Bruno


Le lun. 16 déc. 2019 à 02:09, Kevin Howard <notifications@github.com> a
écrit :

**Comment by brownhoward** [comment]
Hi Bruno,

I certainly agree with you on the Data Browser user experience in comparison to Slack (which I do use) and other professional tools. I'm not a game player so I'll take your word on Call of Duty and Sims. 😄. We are so aware that In fact we have started a project to improve the functionality and UX for  the Data Browser. Still early days but hopefully you will see improvements coming in Q1 2020.

**Comment by csarven** [comment]
Closing issue in favour of addressing through solid-pane and other dokieli issues. The ongoing work on the editor will be in https://github.com/linkeddata/dokieli/milestone/10 .
