### ISSUE TITLE
Can't save to my Solid POD

### ISSUE THREAD

**Issue by TheScooterKing** [dokieli/dokieli#307]
I've been trying to get started with Dokieli, but when I log in to https://dokie.li/ and then try to save it to my pod it comes back with:

Unable to save: you are not authorized.

I've tried adding it to my list of trusted apps, with Read Write Append and Control enabled, but it's still not working. Any idea what's going on?

**Comment by csarven** [comment]
At which URL did you try to "Save" ? Was it at https://dokie.li/ ? Because you don't have write, append, control access to that resource.

**Comment by TheScooterKing** [comment]
I was trying to save from there to my own pod on inrupt.net. It was my understanding that that was the way to get dokeli started on my own instance. If that's not the case, how do I do so?

**Comment by csarven** [comment]
If you want to save a copy of the https://dokie.li/ , you can use "Save As" and specify the URL etc.

or perhaps just do the "Save As" from https://dokie.li/new .. or grab the CSS and JavaScript lines and include that in your own HTML somewhere. dokieli can also work as a browser extension... so you can technically annotate any webpage and store the annotations in your own pod etc..

By the way, perhaps best to move this to dokieli chat: https://gitter.im/linkeddata/chat - happy to help out there.
