### ISSUE TITLE
Convert webm screencast files to mp4 or gif 

### ISSUE THREAD

**Issue by firasm** [dokieli/dokieli#310]
Hello, 

Great project!

I just wanted to let you know that the videos on the home page are currently not viewable on Safari, or on any iOS device that doesn't support webm natively.

I was wondering if the contributors of this project would welcome a PR where I would convert the Webm video files to a more accessible format like mp4 or gif?

If you all feel strongly about keeping the webm format, it would help to at least link out to videos in a different format. 

Here's one example of a webm file converted to a gif:

![dokieli-annotation](https://user-images.githubusercontent.com/2507459/120936814-b6545c80-c6be-11eb-815a-415efb966d0a.gif)

**Comment by csarven** [comment]
Ack. I think the main thing would be to use open media formats/codecs that are also accessible/useful with supporting media, e.g., WebVTT ( https://www.w3.org/TR/webvtt1/ ) used in https://dokie.li/media/track/dokieli.vtt alongside the video https://dokie.li/media/video/dokieli.webm HTML video/track element: https://html.spec.whatwg.org/#the-video-element , https://html.spec.whatwg.org/#the-track-element .

Is there another video format/container that's more suitable without losing the same overall functionality:

```html
<video controls="controls" poster="https://dokie.li/media/images/dokieli-article-fragment.svg" preload="none" width="800">
  <source src="https://dokie.li/media/video/dokieli.webm" type="video/webm">
  <track kind="subtitles" src="https://dokie.li/media/track/dokieli.vtt" srclang="en" label="English" default="default">
</video>
```

**Comment by csarven** [comment]
Thanks again for this issue.

I am noting that as of this writing, WebM is now well-supported across browsers and operating systems: https://caniuse.com/webm . The current screencasts linked from the homepage (and possibly some mentioned in the README in this repository) are using VP8 which is still an issue for older versions of Safari and possibly other browsers. Re-creating the screencasts with WebM and using the VP9 codec should be safe for the foreseeable future.

I have update the comment in https://github.com/linkeddata/dokieli/issues/151 for the broader undertaking of screencasts in dokieli. I've included the main point here on providing an alternative format, e.g., GIF, for certain use cases.
