### ISSUE TITLE
"Not Authorized" to create new documents

### ISSUE THREAD

**Issue by jaxoncreed** [dokieli/dokieli#316]
Hi, in testing Dokieli, I wasn't able to create a new document in my "public" folder after logging in.

Steps to replicate

Sign into a Pod at https://dokie.li/ (I'm using https://jackson.solidweb.org/profile/card#me as my webId, this is an NSS server.)
<img width="1440" alt="Screen Shot 2022-06-22 at 8 28 23 AM" src="https://user-images.githubusercontent.com/5464743/175071902-55f7514d-7a26-428d-b510-63dd8905d80b.png">

Create a new document (I'm using https://jackson.solidweb.me/public/ this should auto-generate a file to save in that folder)
<img width="1440" alt="Screen Shot 2022-06-22 at 8 29 00 AM" src="https://user-images.githubusercontent.com/5464743/175071997-9d6ffdba-f0e3-40ef-b298-aabbd7b8164e.png">

Encounter an error
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5464743/175072094-ef822a1f-ab36-4e7b-977b-9ce25eddd9c2.png">

This is the .acl of the `public` folder

```
# ACL resource for the public folder
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

# The owner has all permissions
<#owner>
    a acl:Authorization;
    acl:agent <https://jackson.solidweb.org/profile/card#me>;
    acl:accessTo <./>;
    acl:default <./>;
    acl:mode acl:Read, acl:Write, acl:Control.

# The public has read permissions
<#public>
    a acl:Authorization;
    acl:agentClass foaf:Agent;
    acl:accessTo <./>;
    acl:default <./>;
    acl:mode acl:Read.
```

**Comment by csarven** [comment]
Thanks for reporting this!

You may have clicked "Sign in" next to the input with your WebID where you may have intended to click on "Sign in" next to "or with OpenID Connect". I am aware that this is confusing and needs a redesign. The one at the top was intended towards WebID+TLS based authentication, whereas the one at the bottom for WebID/Solid OIDC. Can you test with bottom just to be sure?

dokieli currently uses `solid-auth-client`. We are looking into using a more current Solid OIDC library.

**Comment by jaxoncreed** [comment]
Ah, that was the problem. The application works now. Thanks.
