### ISSUE TITLE
Unable to save: you are not authorized

### ISSUE THREAD

**Issue by walves69** [dokieli/dokieli#365]
I created an account at solidweb.org.
I logged into it through the page https://dokie.li/ .
I modified the page and tried to save as, but I get an error of "Unable to save: you are not authorized".
I am using firefox 115.
Is there a problem with login?
Thanks.

![dikielierror2](https://github.com/linkeddata/dokieli/assets/64548095/9e884dd4-4373-4f25-8fa9-35b881168098)

**Comment by VirginiaBalseiro** [comment]
This has been resolved by logging in with OpenID connect (see https://matrix.to/#/!DYkChIUNYFeMUqQhiJ:gitter.im/$0VrnZTAglXapRGCwMMY3pVfP2ZkPRpQZ6G3bmpfNjwM?via=gitter.im&via=matrix.org&via=matrix.freyachat.eu) but we should follow up with improvements to UI / logging in with WebID.

**Comment by csarven** [comment]
Closing issues as there a number of existing issues touching authentication and UI: https://github.com/linkeddata/dokieli/issues?q=is%3Aopen+label%3Aauthentication+label%3AUI
