### ISSUE TITLE
Dokieli embedded in Solid OS not working

### ISSUE THREAD

**Issue by michielbdejong** [dokieli/dokieli#378]
I'm trying to add a Dokieli document to my Solid pod using the built-in Dokieli mint function of Solid OS but run into the following problem:
<img width="1463" alt="Screenshot 2024-02-10 at 17 30 47" src="https://github.com/linkeddata/dokieli/assets/408412/03d2b3c1-bf7a-477e-884c-7bfa64a258fc">

**Comment by michielbdejong** [comment]
Ah wait, is this something that https://github.com/SolidOS/solid-panes/pull/379 fixes maybe?

**Comment by michielbdejong** [comment]
Ah, I was able to work around it through https://dokie.li/new and was able to link my pod and create https://michielbdejong.solidcommunity.net/dokietest - awesome! :)

**Comment by csarven** [comment]
No, I don't think 379 was related to that. Was it? Not sure about the dokielipane.js issue. Glad you worked it out though! (BTW, your /dokietest is a 403 for me but no big deal)
