### ISSUE TITLE
Create CONTRIBUTING

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#386]
There is some information in the README on how to contribute / install that can move to CONTRIBUTING. Leave out documentation to /docs , but see if any information from /docs needs to be here. CONTRIBUTING can link to other stuff, e.g., adding own use to the examples in the wild in the [wiki](https://github.com/linkeddata/dokieli/wiki).

**Comment by VirginiaBalseiro** [comment]
Closed by https://github.com/linkeddata/dokieli/commit/c39c79d82ec1640fc3bafeb7882538f6f5315226
