### ISSUE TITLE
dokieli project org transition

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#388]
As the creator and maintainer of the dokieli project, I'd like to share some ideas about the work going forward:

The [linkeddata Github org](https://github.com/linkeddata/) as dokieli's home has been most excellent since its transfer from just a personal project (which grew out of [csarven/linked-research](https://github.com/csarven/linked-research) ; see also https://csarven.ca/okieli-dokieli for history ).

For the most part, the current setup for the dokieli project under the linkeddata org, which is dear to me, served perfectly fine. That aside, I would like to move this repository to an organisation that's focused on dokieli by 2024-03-22. Here are some key reasons:

* Set up a dedicated organisation for clarifying dokieli's role, identity, and support.
* Use project management tools for organisation and collaboration.
* Improve code modularisation and extensions for sustained project growth; housing related current and future projects under an organisational umbrella.
* Clarify roadmap for ethical and sustainable financial support.

There are no major concerns that I can think of for transferring the repository. GitHub would take care of the redirects and we can update the references to the repository from places where we have access to.

I'd love to hear your thoughts on these points and any other considerations you may have.

**Comment by VirginiaBalseiro** [comment]
I think this is a great idea! Moving the dokieli project to a dedicated organization will provide numerous benefits around project management, and enhance the project's visibility and identity within the community.

**Comment by kjetilk** [comment]
It is great to see the recent flurry of activity! 

I think the most important consideration is whether it would bring others along, as the main advantage is that the tools around review and project management is much better with orgs than personal accounts. With @VirginiaBalseiro 's recent contributions and support, I assume that's taken care of. So, it seems like a reasonable approach to take.

**Comment by timbl** [comment]
Sounds like a good idea

**Comment by csarven** [comment]
Okieli dokieli, created https://git.dokie.li/ and at this time that redirects to https://github.com/dokieli/dokieli/ .
