### ISSUE TITLE
New docs are created silently

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#39]
Upon create, redirect to new document, or open in a new tab, or provide a link to click to open it.

**Comment by rhiaro** [comment]
And if they're opened right away, would be nice to have edit enabled by default

**Comment by csarven** [comment]
Thanks for the issue.

The commits lets the new document load on a new tab/window, focuses on the tab/window, and sets that document mode to edit.

Aside: URLs with query parameter `edit=true` will automatically set the document to edit mode. After it gets set to edit, it will remove the query parameter with the rationale that `edit=true` shouldn't be copy/pasted around, but rather there is a preference to using the canonical URL as much as possible. The intention is to minimize the number of different reference points to the document.
