### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#42]
dokieli needs a logo.
- logo
- favicon

**Comment by rhiaro** [comment]
Here's one full of copyright infringement ;)

![stlogo](https://cloud.githubusercontent.com/assets/466229/12080642/d2e5a4bc-b22e-11e5-95b8-f2c136da873d.png)

**Comment by akuckartz** [comment]
@rhiaro funny :)

**Comment by bshambaugh** [comment]
![flowroot2985](https://cloud.githubusercontent.com/assets/4206177/14967643/63ca5bde-1086-11e6-8535-1b7ffcf77917.png)

**Comment by bshambaugh** [comment]
![dokieli_crop](https://cloud.githubusercontent.com/assets/4206177/14996398/c1f8fae6-1147-11e6-9a2a-a8d9e85d592d.png)  With lowecase letters.

**Comment by bshambaugh** [comment]
![dokieli_three](https://cloud.githubusercontent.com/assets/4206177/14996768/9460e47a-1149-11e6-99fb-b011c6ff8682.png)

**Comment by bshambaugh** [comment]
![dokieli_four](https://cloud.githubusercontent.com/assets/4206177/14996774/a3c22f1e-1149-11e6-855a-40dc97480638.png)

**Comment by bshambaugh** [comment]
![dokieli_six](https://cloud.githubusercontent.com/assets/4206177/14997230/97bc4400-114b-11e6-9735-78ecbe0c2cd1.png)

**Comment by bshambaugh** [comment]
![iconexp](https://cloud.githubusercontent.com/assets/4206177/15003074/749ba552-116d-11e6-8079-6963a07652c4.png)

**Comment by bshambaugh** [comment]
![dokieli_final](https://cloud.githubusercontent.com/assets/4206177/15003376/2551bbec-1179-11e6-89b0-5fd85864e02a.png)

**Comment by bshambaugh** [comment]
![dokieli_final-cropped-small](https://cloud.githubusercontent.com/assets/4206177/15003381/3c432494-1179-11e6-8197-5d7f8f008b29.png)

**Comment by bshambaugh** [comment]
![dokieli_no_overlay](https://cloud.githubusercontent.com/assets/4206177/15166488/61251b68-16ed-11e6-899a-71405bc3a8e2.png)

**Comment by nicola** [comment]
![](http://i.imgur.com/lCNKC2l.png)

**Comment by csarven** [comment]
Going with this for now at least as a favicon.ico, and logo.png (used towards the browser extension icon, not as a "logo" in an article)

![logo](https://user-images.githubusercontent.com/429987/28757334-f9f0ce58-7580-11e7-89ef-bcddc8b94acb.png)

`#009000`

Need to make SVG available.

**Comment by csarven** [comment]
Continued at https://github.com/linkeddata/dokieli/issues/402
