### ISSUE TITLE
Trigger git commits on document updates

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#44]
Eg. if editing a document locally, a script could run that automatically commits to a repo when the document is saved, and/or can be manually triggered from the UI.

**Comment by csarven** [comment]
It'd be great to have a single solution which can handle commits from either local `file:` and `http(s):`. It might not happen, and so, that's okay to have two different solutions. There are browser security issues which would make it hard to trigger commits (for command-line from the browser). Perhaps some browser (default) restrictions can be manually temporarily changed to enable that. Needs clear documentation for the user.

If the user is authenticated with their Github account for example, it should be more straight-forward to that. That of course opens up a whole set of other features/issues to deal with.

**Comment by rhiaro** [comment]
The [gitwatch](https://github.com/nevik/gitwatch) bash script plus periodically export+overwrite works reasonably fine for editing locally for now. I don't think dokieli needs to ship with anything to do this.
