### ISSUE TITLE
Resource navigator and selector

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#60]
For a user to open a resource from their workspace, or to new/save as a resource, .. and possibly even for users to decide where to put their annotation, it'd be useful to have a mini resource navigator.

It can start out with the user's storage / preferencesFile to get a hold of the workspaces, and have the containers and resources be clickable (keyboard actions can be later). Containers open up to reveal whatever they contain (e.g., `ldp:contains`).

This should work along the lines of an OS's GUI file navigator. See also https://github.com/linkeddata/warp -- but it should be far simpler in functionality.

Features: rename/move/delete resources, set ACL.

**Comment by csarven** [comment]
https://github.com/linkeddata/dokieli/issues/61 can be useful here.

**Comment by rhiaro** [comment]
For a user who has not authenticated, and they take an action to trigger the navigator/selector window, they'll need to auth to get the containers to show in the UI. So should it: 
- just ask for a URL to save?
- Or skip to Sign In, then do the rest of Save As? 
  - In which case, should it ask for the WebID? (As if Sign In was clicked).
  - Or just do a simple databox.me auth and use whatever cert is chosen for the WebID, to get the containers?

**Comment by csarven** [comment]
My initial reaction to this is not to interrupt the user's original action (to save). If the input URL is publicly writeable, the process can still be successful even if the authentication fails! So, if for _whatever_ reason it needs to authenticate/sign-in, that can trigger that process, and if successful continue on with the save.
