### ISSUE TITLE
Show annotations on a document from the document's inbox

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#63]
ie. Fetch the inbox for notifications of annotations, then fetch the contents of the annotations from source and display in the right place.

According ACLs of the source annotation of course.

**Comment by csarven** [comment]
Possibly check also the license of the content, which may or may not be suitable for display.

**Comment by csarven** [comment]
dokieli now supports the core feature (fetching, displaying).

Dealing with ACL and licensing are different beasts, so we should handle them as separate issues.
