### ISSUE TITLE
Don't rely on HEAD to authenticate https webids

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#69]
Just because it's https doesn't mean it's on a solid server (eg. could be github.io). Fall back to looking up the storage if there's no User header.

**Comment by csarven** [comment]
Still need to do some refactoring to minimize code, but I think this is mostly resolved (may have missed some corner cases). Tested on Ubuntu/Chromium using both http and https WebIDs on documents on https at dokie.li and databox.me
