### ISSUE TITLE
Check User header matches webID input

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#71]
To help users authenticate as who they intend, ie. if they type one thing then click the wrong cert at the prompt.

As in #70, the cert they choose sets the user, regardless of what is typed in the signin input.

**Comment by csarven** [comment]
Also the UI should only show the user info (e.g., avatar, name, WebID link) at the end of the process when successful.

**Comment by csarven** [comment]
Probably needs extensive testing =)
