### ISSUE TITLE
Sign out button

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#74]
Do we need a sign out button? I suppose it is useful to let the user change profiles, or do stuff anonymously.

It should probably clear the session cookies at the end.

**Comment by rhiaro** [comment]
+1

**Comment by akuckartz** [comment]
:+1:

**Comment by csarven** [comment]
Was implemented ( https://github.com/linkeddata/dokieli/commit/1615fcfa96eda058dbdbbbb8d1726aac7090871e#diff-3bbf637d3a6fe8e950d469c35444acda )
