### ISSUE TITLE
Invalid base IRI from N3Parser for http document and http WebID with fragment

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#75]
When trying to Sign in: if the document is served from an `http` and the WebID input is also `http` (with a fragment), SimpleRDF gives the following error:

```
Error: Invalid base IRI http://csarven.ca/#i
simplerdf.js (line 40121, col 1)
```

If the response of the WebID http request uses `text/turtle` or `application/n-triples`, it uses the N3Parser and gets caught by the `N3Parser.prototype`: `baseIRI.indexOf('#') >= 0` inside `_setBase` which "sets the base IRI to resolve relative IRIs".

If the response of the WebID http request uses `text/html` (HTML+RDFa), there are no issues. Not using the N3Parser in this case any way, but green-turtle.

In cases where the document is served from an `https` and the WebID is either `http` (which goes through an `https` proxy, and the response is in either text/turtle or application/n-triples) or `https`, there are no issues.

Ping @nicola @bergos @RubenVerborgh . Got an insight? Is this a bug in N3Parser? I would have expected it to work around the fragment.

**Comment by RubenVerborgh** [comment]
N3.js is right to give this error, for the reason it states. You have to remove the fragment before using something as a base IRI.

**Comment by csarven** [comment]
@RubenVerborgh Thanks. I had the expectation that this should have been quietly handled by the libraries.
