### ISSUE TITLE
RDFa missing when exporting "data -> embed"

### ISSUE THREAD

**Issue by dr0i** [dokieli/dokieli#79]
Add some turtle using the UI `data -> embed`. Click on `save`. Then `export` the html. The newly generated triples are missing in the RDFa of the new html document.

**Comment by csarven** [comment]
Thanks for the report @dr0i .  It was a minor regression bug.

**Comment by dr0i** [comment]
Cool, thx for the fast fix!

**Comment by dr0i** [comment]
Hm, triples are there now, but not as RDFa. If I query the document, using a standard tool like `rapper`, the triples are not parsed (as they are in fact not RDFa):

```
rapper -i rdfa http://127.0.0.1/...html
```

This is a snippet of the html-source with the triple:

```
<script id="meta-turtle" type="text/turtle" title="Turtle"># <!--//--><![CDATA[//><!--
<test> <http://dcterms.de/creator> <http://lobid.org/team/pc> .
# //--><!]]></script></head>
```

For what is this good if it cannot be queried?

**Comment by csarven** [comment]
Good question. I suppose what you want in the end is to just parse the document and get all the RDF out of it without having to worry about the the formats. This is entirely up to the parser however.

The triples entered via the 'Embed' UI are not RDFa-ized (i.e., they are not transformed to RDFa). They are hidden data islands - at least initially - in Turtle/N-Triples, JSON-LD, TriG, and we let these embedded data blocks reside on their own. They are not meant to be prose content, as it is primarily the case with RDFa.

The RDF entered in the Embed can be used to ship raw data with the article. It can be re-used by the interface as it sees fit. Other interfaces (not necessarily dokieli's) can also use them. I think the use cases around that are sufficient enough that we don't have to transform the RDF serialization in there to RDFa. The idea is to let RDFa take care of the data/text that's usually exposed/visible to a human. RDFa annotation will be part the core UI. See also issue https://github.com/linkeddata/dokieli/issues/54 .

There are parsers which can extract Turtle, JSON-LD, or TriG out of the HTML documents e.g., [RDF Distiller](http://rdf.greggkellogg.net/distiller), [Google's Structured Data](https://developers.google.com/structured-data/testing-tool/), [OpenLink's Structured Data Sniffer](https://github.com/openlink/structured-data-sniffer) or [URIBurner](http://linkeddata.uriburner.com/). As far as I know, rapper's librdf can't at this time. So, your Turtle is fine, it is the parser that you have to worry about.

You might also want to briefly look at:
- http://www.w3.org/TR/turtle/#in-html
- http://www.w3.org/TR/json-ld/#embedding-json-ld-in-html-documents

I hope this addresses your inquiry/concern.

**Comment by dr0i** [comment]
Thx for the detailed explanation! So I indeed misunderstood what "data embed" is about, and I am looking forward the RDFa annotation coming with #54 .
Thx also for hinting other libraries which can parse all the triples :+1:

**Comment by csarven** [comment]
If you misunderstood, we should take that as a chance to improve the UI. Perhaps for starters the actions label and button needs a revision: 'Data [Embed]', or have a sentence in the embed data container stating its purpose or what will happen. Will keep this in mind on next visit to the embed data UI. Open for suggestions.

See also https://github.com/linkeddata/dokieli/issues/37 which is about improving the UI for Nanopublications (not as generic as Turtle/JSON-LD).

**Comment by dr0i** [comment]
+1
