### ISSUE TITLE
Copying article inboxes

### ISSUE THREAD

**Issue by csarven** [dokieli/dokieli#92]
When a resource is `save as`ed to a new location, should it copy over all of its inboxes (and its contents) to the new location?

What are the implications for doing or not doing?

[I'm leaning on not copying since the notifications which were made to the original inbox are for that inbox.. I can't think of a strong reason to copy them over. If the operation was a 'move', then it'd make more sense. Documenting this for the future.]

**Comment by rhiaro** [comment]
I would say definitely not! That's like stealing someone else's notifications.

**Comment by csarven** [comment]
If the user has rights to copy, is it stealing?

**Comment by rhiaro** [comment]
That aside, the notifications were intended for the original document, not an amended versions. I can't think of a good reason to copy them.

**Comment by csarven** [comment]
If the article's inbox URL is not changed in the Save As operation, then the new copy will still point to it and reuses it. The operation is on the article (as opposed to the inbox), so there is no need to do anything further. There is an exception to this: relative CSS, JavaScript, and img URLs referenced in HTML are copied.

**Comment by rhiaro** [comment]
What does "changed in the Save As operation" mean? How does one do this? Someone might not realise the article they copied has an inbox, and then notifications sent in future to the article will invisibly go into someone else's inbox. Maybe a [ ] use the same inbox checkbox?

It's another issue that there's no way in the UI to set/change an inbox still, anyway.

**Comment by csarven** [comment]
"changed in the Save As operation" -- I meant prior to Save As being triggered or while it is being processed.

It is up to the inbox to decide which notifications remain. Many targets may point to the same inbox, so, it is not something that needs to be addressed from dokieli. It is the user's responsibility to keep an eye on what's in the article (including the inbox statement).

`[] use the same inbox (or specify): ___` option in Save As prompt seems reasonable to me. That's a separate issue/feature however. This is a bit borderline in terms of information that should be influenced through Save As, as opposed to something (i.e., some statements in the article) that should be updated directly in the article. I can see that stuff like this can be a speciality/convenient to do from save as prompt.

**Comment by rhiaro** [comment]
> "It is up to the inbox to decide which notifications remain." 

If Stranger X copies my article and keeps pointing to my inbox because they don't know better, I could get flooded with their nofifications and that would be very inconvenient for me. I can resolve it retroactively by filtering them out, but we should minimise the likelihood of this occurring in the first place.

>  "It is the user's responsibility to keep an eye on what's in the article (including the inbox statement)"

Stranger X doesn't know what an inbox is, or how to change it, since there's nothing in the UI. Again, it is our responsibility to minimise the chances of mistakes like this happening.
